// Code generated by "esc -ignore '^\..*' -o static.go static/"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/static/app.js": {
		local:   "static/app.js",
		size:    2734,
		modtime: 1507460718,
		compressed: `
H4sIAAAAAAAC/6xWf2/bNhD9W/oUNwJrqdlR7aAIthhq0KUB2iE/gDpfgBHPkRCKFEjajjHkuw8kJVmW
1TTA+o8h8j3y3t09kl6tZW5LJYGvNXMfVJoE/o2jDdPwDBncMFukK6GUptJ8mONfySKABjJ4ht/hbLaI
owHz+cPZrOVVb+QVDe/0YzPBh9zTj46r0a61BEo5fIJZAhfAYQKEEzgHQhKYAKVFCxUOKvpQ1UKVg6o9
ZNzYkEX8EsddVYRi/F6z/MnQrirWjyGDf5Z3t2nNtEEqVM7E0irNHjF9RPvNYkVJYJLEye5WNR8X7cc5
SNzCZ63Zjvby01ipDd4JTgNvCn8mh9qMVRobcYHjJR5IMQMp0yDaWF3Kx3K1axf2AoeZw1DHYop9OSCD
L8xiKtWWJnACtIA/4GzW/sxns9nR9umqFBY1bSPQ0mLlt2x5fstQXIelS0SZwCewizh6GVRiXXNmkXJm
2XGX+i1snIsoIYMVEwa7zqQVq8fklCsIAi4FMwayDFyYZvTuHXjsllXYQW4Q1kZNJKvXLlAUefLn3JYb
hElDD8M9vAxrPOa+HfIScvZifjO+Em7/Rnm9NkVI3tWmS8gobfcZsSk8HBT4oRVyAj0RL71WjRhsaIta
sBwpCqxQ2inkSlqU1sfZFqVAaLG0YOayKAW/VRwNTYKUFgz+8ni3QDBj/UyTVTvP6holD9w23lBWrjQ/
OBTeEexBoKusytd+p1wjs3gV9qXE46S7jpC5C8hPNsz7r8g4TdJSGtT2u9pSb2zHbOYuUQg6cwyJ+uv9
zTVkQLxVyAhxPiA644zxTge8ZY3Skp8612Wh1bZLYi/7ZO50R1ptX9G9N/0Idz7CdfJHqAP13TvTOwvJ
3njBUF2LHtE2/fl7941T0rSWJNOQ1KDzuZOL/7PzVlkmIINZ7wFzV/QNq2nypqpvIIPKae/dHL7iDtjA
BWzg3G8fVe6G7rGmsIEJDEoTBUWTrA+0JavSldJXLC/2YjZMrHEKT7j7JUZ4wt3PHdC11QfvGtrV8/sr
8VvCa4fo3nFI75/B2CK/G09LhxPbruDjQj3+JtM1rvqR6XhpasF2fdMNbqBFHA2cObQtMk2PX+9m3pM7
dYzzqw1Ke10aixI1ff/l7uYyXITXinHk76fQeeH199BV51D9InZ9i/0zaTWy1vw+5FKtdY6UoBsYd2Di
QDoWRdwrRXpC8FhJ82z3/kZh6p+xH+r6LwAA//+qr28drgoAAA==
`,
	},

	"/static/favicon.ico": {
		local:   "static/favicon.ico",
		size:    1150,
		modtime: 1507462465,
		compressed: `
H4sIAAAAAAAC/7RTS6txURh+ldk30Tc4Y8Pz085PMFD+iDIgY6VkoEQSkeSaexQi93K/PKdnae32djA5
nae0XuvyPpe1tohNbOJwcHTKl13kQ0Q+RcQhIk65zyvYRf7/u/808Aa3280Ydf1XMHMR+/0e8/kc2+0W
4/FY1ZfLBcfjEdfr9el5s87JZAKv14t2u41+v49er4d4PI5QKPTyvHmsVCrodruWOWrJZrOqt3le17vd
TtWDwQA+n89YI5/mpP5yuWzhPhwO2Gw2WK/XyiNRr9eRz+cxGo2M/roHdXG/xmq1Upqm06nKif2KxaLy
3Wq1ftwh9y4Wi5cZMLNGo2Fo12e1NmrSGTzLvlAoKJ+Pa+zFDFOpFJLJpOU8e3Ok9k6nY/FWKpUwHA4R
i8XgcrkQiURQq9Usmqknk8moXHRm5NP7AoEAPB4PgsEgwuGwsU7QK3M6nU5qjrnPZjO1Rl5qdrvdSKfT
iEaj8Pv9Fv+8t+VyaeipVqvI5XJoNpvqHdEvPSQSCfUGWZPrVf5a1/l8Vn14j/REHvNbeszf/P/dN6Lv
lJBf4jsAAP//eo1wxn4EAAA=
`,
	},

	"/static/index.html": {
		local:   "static/index.html",
		size:    454,
		modtime: 1507462563,
		compressed: `
H4sIAAAAAAAC/1yRvXLrIBCFa/kpuFQ3hU2bAqlxMimTIk1KBKtobQQadq2R3j4DyDOJK/bvfHt20P9e
3s+fXx+vYuTJdwddn0aPYFx3aBrNyB66txhAqxrn6gRshB1NIuBW3ng4PsvS8BiuIoFvJfHmgUYAlmJM
MOyVkyWSgrcZWsmwssr5gxRtDHfRYJacntDGuwwn8w1qPZaxIiWbcGZBybbSzPPp8nfFxSymjshOqxrl
I9V+pe6j2wrIEDoQ6FrZx7WwG+1wKRXrDRFQRjhcaq+/MccgYrAe7TXPgEn/n2R3zoFWtV/QqrCrXbCM
MVRqDAyBH3YlsDG537u02lXFeDWsVf2unwAAAP//oHywC8YBAAA=
`,
	},

	"/static/style.css": {
		local:   "static/style.css",
		size:    567,
		modtime: 1507324092,
		compressed: `
H4sIAAAAAAAC/3SQ38rbMAzFr+OnEITybTBDk5VuOC+w11BsJTFV7GKrf7LRdx8xXddCvyuBdPQ7h9NH
t8AfVQ0xiB5w9rwY+PhFfCbxFj++QcaQdabkh+4uy/43GcgzMlPqVDVjGn0w0G5gv+nUTWH2jgqVI4qB
5MdJ1kPdx+u672NylAzI5APkyN5BvWt/4q7tVNWjPYwpnoIzUNMwDLQ6H9E5H0YDDc0PT800yH11U3Ui
G5PLIMkEmbSdPLsvdKbwtZi+cqlwn7/c01dbXi7eyWSg2W43naouMTndJ8KDgTI0Mn+O+F4QQlfRyH4M
zz1IFOT/TWiJx5c2ekZ7KErLmDO9TfcWjY+LW0Oh+BgMhBioU5WNHJOBem9/NJZW+amkYJ9FZ1mYtCxH
+qe/KXHr+dH9Fhq6rvu/AQAA//8X8r0qNwIAAA==
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/static": {
		isDir: true,
		local: "static",
	},
}
